apiVersion: v1
kind: Namespace
metadata:
  name: syndeno-collector

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: collector
  namespace: syndeno-collector

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: syndeno-collector-cluster-role
rules:
  - apiGroups: [""]
    resources: ["namespaces", "events"]
    verbs: ["get", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: syndeno-collector-cluster-bind
  namespace: syndeno-collector
subjects:
- kind: ServiceAccount
  name: collector
  namespace: syndeno-collector
roleRef:
  kind: ClusterRole
  name: syndeno-collector-cluster-role
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: syndeno-collector
  labels:
    app: syndeno-collector
    language: go
    function: kubernetes-event-collector
  namespace: syndeno-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syndeno-collector
  template:
    metadata:
      labels:
        app: syndeno-collector
    spec:
      containers:
      - name: syndeno-collector
        image: daniels7/collector:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 200m
            memory: 300M
      serviceAccount: collector  